apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: o06orjx10-nodejs
  janus-idp.io/tekton: o06orjx10-nodejs
  backstage.io/kubernetes-id: o06orjx10-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: o06orjx10-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
